### 
# This playbook deploys the whole application stack in this site. 
## 
- name: apply common configuration to server 
  hosts: all 
  user: ubuntu 
  roles: 
    - common 
 vars:
    project_path: "{{ host_project_path|default('/CI/prod') }}"
